// Generated by Cypress Author on 2026-07-30.
describe('Check "Speaker Kit" area', () => {
  it('navigates from About → speaker kit', () => {
    cy.visit('/about/');
    cy.waitForHydration();

    cy.get('[data-cy=SpeakerKitCta]').scrollIntoView();
    cy.get('[data-cy=ButtonToSpeakerKit]').click();

    cy.location('pathname').should('eq', '/speaker-kit/');
    cy.get('[data-cy=SpeakerKit]').should('be.visible');
  });

  it('navigates from Speaking → speaker kit', () => {
    cy.visit('/talks/');
    cy.waitForHydration();

    cy.get('[data-cy=SpeakerKitCta]').scrollIntoView();
    cy.get('[data-cy=ButtonToSpeakerKit]').click();

    cy.location('pathname').should('eq', '/speaker-kit/');
    cy.get('[data-cy=SpeakerKit]').should('be.visible');
  });

  it('renders all speaker kit sections → each block is visible', () => {
    cy.visit('/speaker-kit/');

    cy.get('[data-cy=KitIntro]').should('be.visible');
    cy.get('[data-cy=KitStats]').should('be.visible');
    cy.get('[data-cy=KitMap]').should('be.visible');
    cy.get('[data-cy=KitBios]').should('be.visible');
    cy.get('[data-cy=KitPhotos]').should('be.visible');
    cy.get('[data-cy=KitTalks]').should('be.visible');
    cy.get('[data-cy=KitAchievements]').should('be.visible');
    cy.get('[data-cy=KitContact]').should('be.visible');
  });

  it('shows the speaking map → highlighted countries match the legend', () => {
    cy.visit('/speaker-kit/');

    cy.get('[data-cy=SpeakingMap]').should('be.visible');

    // Legend and map highlights come from the same country list, so their
    // counts must match. Asserted as an invariant (plus a floor) so adding a
    // country later doesn't break the test.
    cy.get('[data-cy=SpeakingMap] .speaking-map__list li').then(($legend) => {
      expect($legend.length, 'countries in legend').to.be.at.least(22);
      cy.get('[data-cy=SpeakingMap] .speaking-map__svg .visited')
        .should('have.length', $legend.length);
    });

    // A visited country is painted in the brand colour; an unvisited one is not.
    cy.get('#de').should('have.class', 'visited');
    cy.get('#cn').should('not.have.class', 'visited');
  });

  it('copies a bio → button confirms with "Copied!"', () => {
    cy.visit('/speaker-kit/');
    cy.waitForHydration();

    cy.get('[data-cy=CopyBioShort]').should('contain.text', 'Copy');

    // The click handler is wired up during hydration, which can land a tick
    // after the app first mounts. Re-query and re-click on each retry until the
    // label flips, so the test doesn't race a not-yet-interactive button.
    cy.get('[data-cy=CopyBioShort]').should(($btn) => {
      $btn[0].click();
      expect($btn.text()).to.contain('Copied!');
    });
  });

  it('offers photo downloads → download links point at image files', () => {
    cy.visit('/speaker-kit/');

    cy.get('[data-cy=KitPhotos] a[download]')
      .should('have.length', 4)
      .first()
      .should('have.attr', 'href')
      .and('match', /\.(webp|jpg|jpeg|png)$/);
  });
});
